#!/usr/bin/env python3

import sys
import sqlite3
import subprocess

if len(sys.argv) < 2:
    print("Usage: nutrition FILE")
    sys.exit(1)

db_path = sys.argv[1]
log_table = ''
foods_table = ''

def main():
    print_nutrition_report(today)
    insert_log_entry()
    print_nutrition_report(selection)
    insert_new_food()



def print_nutrition_report(date):
    print_nutrition_stats(date)
    print_log_entries(date)




def insert_log_entry():
    return






def insert_new_food():
    return






def print_nutrition_stats(date):
    return






def print_log_entries(date):
    print_report()
    return






def issue_sql_statement(db, statement):
    con = sqlite3.connect(db)
    cur = con.cursor()
    cur.execute(statement)
    con.commit()
    con.close()

def print_report(db, statement):
    # SELECT statements are run via shell to produce the "-box" output format
    subprocess.run([f"sqlite3 -box {db} '{statement}'"], shell=True)

main()
